### ISSUE TITLE
Volumes doesn't work

### ISSUE THREAD

**Issue by zot24** [erikcw/docker-lapis#2]
If I add a volumes to the Docker container like below::

```
lapis:
  volumes:
    - "/vagrant/src:/opt/openresty/nginx/conf"
  build: ../dockerfiles/lapis/.
  ports:
    - "9000:8080"
```

It will first create the container and run `lapis new` and then attach the volumes so we'll end overlapping `opt/openresty/nginx/conf` with our code but won't be able to run `lapis new` until the container got created.

What could be the best way to solve this?
